/**
 * PDF complaint export — pdfkit
 */

import PDFDocument from 'pdfkit';

const SAFFRON = '#e8621a';

/**
 * @param {object} complaint - DB row (camelCase from getComplaintByTrackingId)
 */
export function generateComplaintPDF(complaint) {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 72, bottom: 72, left: 72, right: 72 },
  });
  const chunks = [];
  doc.on('data', (c) => chunks.push(c));

  const tid = complaint.trackingId || '—';
  const lang = complaint.language || 'en';
  const sev = (complaint.severity || 'medium').toUpperCase();
  const pageW = doc.page.width;
  const left = 72;
  const contentW = pageW - 144;

  doc.font('Helvetica-Bold').fontSize(24).fillColor('#111');
  doc.text('AWAAZ AI — آواز', left, 72, { width: contentW, align: 'left' });
  doc.font('Helvetica').fontSize(10).fillColor('#666');
  doc.text('OFFICIAL COMPLAINT DOCUMENT', left, 72, { width: contentW, align: 'right' });
  let y = 72 + 32;
  doc.strokeColor(SAFFRON).lineWidth(2).moveTo(left, y).lineTo(pageW - left, y).stroke();
  y += 16;

  doc.rect(left, y, contentW, 36).fill('#f0f0f0');
  doc.fillColor('#111').font('Courier-Bold').fontSize(11);
  doc.text(`TRACKING ID: ${tid}`, left + 8, y + 10, { width: contentW - 16 });
  y += 44;

  doc.font('Helvetica').fontSize(9).fillColor('#444');
  doc.text(`Generated: ${new Date().toISOString().slice(0, 10)}  |  Language: ${lang}  |  Severity: ${sev}`, left, y);
  y += 28;

  const meta = [
    ['Issue Type', complaint.issueType || '—'],
    ['Department', complaint.department || '—'],
    ['Severity', complaint.severity || '—'],
    ['Submit To', complaint.submitTo || '—'],
  ];

  meta.forEach(([label, val], i) => {
    const rowH = 28;
    if (i % 2 === 0) {
      doc.rect(left, y, contentW, rowH).fill('#f8f8f8');
    }
    doc.fillColor('#111').font('Helvetica-Bold').fontSize(10).text(label, left + 8, y + 8, { width: 110 });
    doc.font('Helvetica').fontSize(10).text(String(val), left + 120, y + 8, { width: contentW - 128 });
    y += rowH;
  });
  y += 12;

  doc.font('Helvetica-Bold').fontSize(12).fillColor('#111').text('COMPLAINT LETTER', left, y, { underline: true });
  y += 22;
  doc.font('Times-Roman').fontSize(11).lineGap(4).fillColor('#222').text(complaint.englishLetter || '—', left, y, {
    width: contentW,
    align: 'left',
  });
  y = doc.y + 16;

  doc.font('Helvetica-Bold').fontSize(12).text('شکایتی خط (Urdu)', left, y, { underline: true });
  y += 18;
  doc.font('Helvetica').fontSize(9).fillColor('#666').text(
    '(Urdu text — view in the Awaaz AI app for proper RTL rendering)',
    left,
    y,
    { width: contentW, italic: true }
  );
  y = doc.y + 8;
  doc.font('Times-Roman').fontSize(11).fillColor('#222').text(complaint.urduLetter || '—', left, y, {
    width: contentW,
  });

  const footerY = doc.page.height - 56;
  doc.font('Helvetica').fontSize(8).fillColor('#888');
  doc.text('Generated by Awaaz AI — awaaz-ai.in', left, footerY);
  doc.text('This document was auto-generated. Verify department details before submission.', left, footerY + 12);
  doc.text('Page 1', pageW - left - 40, footerY, { width: 40, align: 'right' });

  doc.end();

  return new Promise((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}
